# Generated by Django 5.2 on 2025-04-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-feedback_date'], 'verbose_name_plural': 'User Progress'},
        ),
    ]
